// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDozI9LDXFPfe0g5mQEPdhzRwCk5xfMYFM',
    appId: '1:946262493532:web:c83069e9d209de74d49999',
    messagingSenderId: '946262493532',
    projectId: 'ropay-ac1d2',
    authDomain: 'ropay-ac1d2.firebaseapp.com',
    storageBucket: 'ropay-ac1d2.firebasestorage.app',
    measurementId: 'G-JTZQJV8K1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvM-9P5s-CBUJ7cpLd4lp3eccixqg8--M',
    appId: '1:946262493532:android:c5a22ad519165a7ad49999',
    messagingSenderId: '946262493532',
    projectId: 'ropay-ac1d2',
    storageBucket: 'ropay-ac1d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSvfqIKO5pvC1EyGQ6XwxOsmkSIPTXuE',
    appId: '1:946262493532:ios:dfccfd2a7b5bb095d49999',
    messagingSenderId: '946262493532',
    projectId: 'ropay-ac1d2',
    storageBucket: 'ropay-ac1d2.firebasestorage.app',
    iosBundleId: 'com.example.ropayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSvfqIKO5pvC1EyGQ6XwxOsmkSIPTXuE',
    appId: '1:946262493532:ios:dfccfd2a7b5bb095d49999',
    messagingSenderId: '946262493532',
    projectId: 'ropay-ac1d2',
    storageBucket: 'ropay-ac1d2.firebasestorage.app',
    iosBundleId: 'com.example.ropayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDozI9LDXFPfe0g5mQEPdhzRwCk5xfMYFM',
    appId: '1:946262493532:web:af1b9e63c88b4cdfd49999',
    messagingSenderId: '946262493532',
    projectId: 'ropay-ac1d2',
    authDomain: 'ropay-ac1d2.firebaseapp.com',
    storageBucket: 'ropay-ac1d2.firebasestorage.app',
    measurementId: 'G-3XRBQRH6JJ',
  );
}
