import 'package:get/get.dart';

class LocalStrings extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_title': 'RoPay',
          'mqtt_example_title': 'MQTT Example',
          'mqtt_connecting': 'Connecting to MQTT Broker...',
          'mqtt_connected': 'Connected to MQTT Broker',
          'mqtt_disconnected': 'Disconnected from MQTT Broker',
          'data_packet_received': 'Data Packet Received',
          'settings_title': 'Settings',
          'account': 'Account',
          'notification': 'Notification',
          'greeting': 'Welcome,',
          'ph_level': 'Water pH Level',
          'temperature': 'Temperature',
          'water_quality_index': 'Water Quality Index',
          'filter_life': 'Filter Life',
          'plan_expiry_date': 'Plan Expiry Date',
          'subscriptions_title': 'Subscriptions',
          'basic_plan': 'Basic Plan',
          'pro_plan': 'Pro Plan',
          'premium_plan': 'Premium Plan',
          'basic_plan_features': 'Track water usage for 1 device, Monthly usage reports, Basic customer support, 10% discount on repairs',
          'pro_plan_features': 'Track water usage for up to 3 devices, Detailed monthly & weekly reports, Priority customer support, 20% discount on repairs, Leak detection alerts',
          'premium_plan_features': 'Track water usage for unlimited devices, Real-time usage analytics, 24/7 premium support, 30% discount on repairs, Advanced leak & wastage alerts, Custom water-saving tips',
          'logout': 'Logout',
          'language': 'Language',
          'help': 'Help',
          'payment': 'Payment',
          'subscribe_now': 'Subscribe Now',

        },
        'hi_IN': {
          'app_title': 'रोपे',
          'mqtt_example_title': 'MQTT उदाहरण',
          'mqtt_connecting': 'MQTT ब्रोकर से कनेक्ट हो रहा है...',
          'mqtt_connected': 'MQTT ब्रोकर से कनेक्टेड',
          'mqtt_disconnected': 'MQTT ब्रोकर से डिस्कनेक्टेड',
          'data_packet_received': 'डेटा पैकेट प्राप्त हुआ',
          'settings_title': 'सेटिंग्स',
          'account': 'खाता',
          'notification': 'सूचना',
          'greeting': 'स्वागत है,',
          'ph_level': 'पानी का पीएच स्तर',
          'temperature': 'तापमान',
          'water_quality_index': 'पानी की गुणवत्ता सूचकांक',
          'filter_life': 'फ़िल्टर जीवन',
          'plan_expiry_date': 'योजना समाप्ति तिथि',
          'subscriptions_title': 'सदस्यताएँ',
          'basic_plan': 'बेसिक योजना',
          'pro_plan': 'प्रो योजना',
          'premium_plan': 'प्रीमियम योजना',
          'basic_plan_features': '1 डिवाइस के लिए पानी की खपत ट्रैक करें, मासिक उपयोग रिपोर्ट, बुनियादी ग्राहक सहायता, मरम्मत पर 10% छूट',
          'pro_plan_features': '3 डिवाइस तक पानी की खपत ट्रैक करें, विस्तृत मासिक और साप्ताहिक रिपोर्ट, प्राथमिकता ग्राहक सहायता, मरम्मत पर 20% छूट, लीक डिटेक्शन अलर्ट',
          'premium_plan_features': 'असीमित डिवाइस के लिए पानी की खपत ट्रैक करें, रीयल-टाइम उपयोग विश्लेषण, 24/7 प्रीमियम समर्थन, मरम्मत पर 30% छूट, उन्नत लीक और बर्बादी अलर्ट, कस्टम पानी-बचत सुझाव',
          'logout': 'लॉगआउट',
          'language': 'भाषा',
          'help': 'मदद',
          'payment': 'भुगतान',
          'subscribe_now': 'अभी सदस्यता लें',
        }
      };
}